apiVersion: apps/v1
kind: Deployment
metadata:
    name: petclinic-deployment
    labels:
       app: petclinic-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
   matchLabels:
     app: petclinic-app
  template:
   metadata:
     labels:
       app: petclinic-app
   spec:
     containers:
     - name: petclinic
       image: manojd123/petclinicprivate
       ports:
        - containerPort: 8080
     
        

---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
spec:
   type: NodePort
   selector:
       app: petclinic-app
   ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
